name: Build Container
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: 'latest'
  schedule:
    - cron: "* 12 * * 0"  # Monday at 4AM
defaults:
  run:
    working-directory: ./
jobs:
  ocp-build:
    runs-on: ubuntu-latest
    steps:
      - name: Image Build
        # if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master'
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'start-build --follow -n bcgov-tools patroni-postgres'
            'tag -n bcgov-tools bcgov-tools/patroni-postgres:12.4-latest bcgov-tools/patroni-postgres:12.4-${{ github.event.inputs.version }}'
      # - name: Additional Tag
      #   if: github.event_name != 'schedule' && github.ref == 'refs/heads/master'
      #   uses: redhat-developer/openshift-actions@v1.1
      #   with:
      #     version: "latest"
      #     openshift_server_url: ${{ secrets.OpenShiftServerURL}}
      #     parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
      #     cmd: |
      #       'version'
      #       'tag -n bcgov-tools bcgov-tools/patroni-postgres:12.4-latest bcgov-tools/patroni-postgres:12.4-${{ github.event.inputs.version }}'
